In [11]:
import pandas as pd

In [12]:
df = pd.read_csv(r"C:\Users\PROBOOK 430 G2\Documents\Hospital_Data.csv")

In [13]:
df.describe()

,Age,Experience,Salary,Performance_Score,Attendance
count,50000.000000,50000.00000,5.000000e+04,49916.000000,50000.000000
mean,42.461060,5.50650,2.510861e+06,0.749677,0.749747
std,13.255999,2.88243,1.522194e+06,0.147201,0.146772
min,20.000000,1.00000,7.800000e+01,0.500000,0.500000
25%,31.000000,3.00000,1.235918e+06,0.620000,0.620000
50%,42.000000,6.00000,2.491594e+06,0.750000,0.750000
75%,54.000000,8.00000,3.751618e+06,0.880000,0.880000
max,65.000000,10.00000,1.200000e+07,1.000000,1.000000

In [14]:
#Filling the missing performance score with the mean of each department
df['Performance_Score'] = df['Performance_Score'].fillna(
    df.groupby('Department')['Performance_Score'].transform('mean'))

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Staff_ID           50000 non-null  object
 1   Age                50000 non-null  int64
 2   Gender             50000 non-null  object
 3   Department         50000 non-null  object
 4   Job_Title          50000 non-null  object
 5   Experience         50000 non-null  int64
 6   Salary             50000 non-null  int64
 7   Training           50000 non-null  object
 8   Performance_Score  50000 non-null  float64
 9   Hospital_Type      50000 non-null  object
 10  State              50000 non-null  object
 11  State_ID           50000 non-null  object
 12  Attendance         50000 non-null  float64
dtypes: float64(2), int64(3), object(8)
memory usage: 5.0+ MB

In [17]:
#Finding the limits.
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

upper_limit = Q3 + 1.5 * IQR
lower_limit = Q1 - 1.5 * IQR
print('Upper_limit:', upper_limit)
print('Lower_limit:', lower_limit)

Upper_limit: 7525168.625
Lower_limit: -2537632.375

In [18]:
#Finding the outliers
df.loc[(df['Salary'] > upper_limit)| (df['Salary'] < lower_limit)]

,Staff_ID,Age,Gender,Department,Job_Title,Experience,Salary,Training,Performance_Score,Hospital_Type,State,State_ID,Attendance
350,STT_10225,49,Male,Obstetrics & Gynaecology(O&G),Admin Officer,9,12000000,Yes,0.980000,Federal,Plateau,NIG140,0.50
445,STT_10310,49,Female,Public Health,Cleaner,5,12000000,Yes,0.710000,Teaching,Niger,NIG132,0.61
761,STT_10596,25,Male,Laboratory,Laboratory Scientist,10,12000000,Yes,0.751832,Private,Bauchi,NIG130,0.61
1154,STT_1095,50,Female,Peadiatrics,Cleaner,7,12000000,No,0.760000,Teaching,Jigawa,NIG119,0.70
1464,STT_11229,41,Male,Transport/Ambulance,Radiographer,10,12000000,Yes,0.500000,State,Enugu,NIG128,0.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49497,STT_9542,42,Male,Administration,IT Officer,5,12000000,No,0.560000,Federal,Ondo,NIG115,0.78
49619,STT_9653,28,Female,Dental,Physiotherapist,7,12000000,Yes,0.650000,Private,Ekiti,NIG133,0.71
49650,STT_9681,59,Female,Radiology,Physiotherapist,2,12000000,No,0.940000,Teaching,Delta,NIG122,0.79
49875,STT_9886,29,Male,Neurology,Security,4,12000000,Yes,0.840000,Federal,Ogun,NIG123,0.79
49992,STT_9992,61,Female,Psychiatry,Laboratory Scientist,6,12000000,Yes,0.660000,State,FCT,NIG120,0.75

In [9]:
df['Salary'] = df['Salary'].astype(float)

In [19]:
#Capping the outliers.
df_capped = df
df_capped.loc[df_capped['Salary']> upper_limit, 'Salary'] = upper_limit
df_capped.loc[df_capped['Salary']< lower_limit, 'Salary'] = lower_limit

C:\Users\PROBOOK 430 G2\AppData\Local\Temp\ipykernel_15060\2077971750.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '7525168.625' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_capped.loc[df_capped['Salary']> upper_limit, 'Salary'] = upper_limit

In [20]:
#Dropping duplicates in Staff_id
df= df.drop_duplicates('Staff_ID')

In [21]:
df.shape

(49976, 13)

In [11]:
# Save to Documents folder
df.to_csv(r'C:\Users\PROBOOK 430 G2\Documents\Golden_Dataset.csv', index=False)